/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Tubes;

import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thinkpad
 */
public class AppBuku extends javax.swing.JFrame {

    
    private DefaultTableModel model  = new DefaultTableModel();
    private Connection conn;
    private ArrayList<Buku> daftarBuku;
    
    /**
     * Creates new form AppBuku
     */
    public AppBuku() {
        initComponents();
        loadKolom();
        jtBuku.setModel(model);
        conn = Koneksi.bukaKoneksi();
        loadBuku();
        tampilBuku();
    }
    
    private void loadKolom(){
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Kategori");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfJudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPengarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        bSubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBuku = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Buku"));

        jLabel2.setText("Judul:");

        jLabel3.setText("Pengarang:");

        jLabel4.setText("Kategori:");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Genre-", "Romantis", "Horor", "Komedi", "Misteri", " " }));

        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(tfJudul)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(bSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSubmit)
                    .addComponent(jButton2))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Buku"));

        jtBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtBuku);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Data Buku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class Koneksi{
        
        private static Connection conn;
        private static final String DB_DRIVER = "com.mysql.jdbc.Driver";
        private static final String DB_NAME = "db_desktop";
        private static final String DB_URL = "jdbc:mysql://127.0.0.1:3306" + DB_NAME;
        private static final String DB_UNAME = "root";
        private static final String DB_PASS = "";

        public static Connection bukaKoneksi(){
            if(conn == null){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    conn = DriverManager.getConnection(DB_URL, DB_NAME, DB_PASS);
                }catch(ClassNotFoundException e){
                    System.err.format("Class not found");
                }catch(SQLException e){
                    System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());                
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            return conn;
        }
    }
    
    public class Buku{
        private int id;
        private String judul, pengarang, kategori;
    
        public Buku(int id, String judul, String pengarang, String kategori){
            this.id = id;
            this.judul = judul;
            this.pengarang = pengarang;
            this.kategori = kategori;
        }
        
        public int getId(){
            return id;
        }
                
        public String getJudul(){
            return judul;
        }
                
        public String getPengarang(){
            return pengarang;
        }
                
        public String getKategori(){
            return kategori;
        }
    }
    
    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        // TODO add your handling code here:
        String judul = tfJudul.getText();
        String pengarang = tfPengarang.getText();
        String kategori = cbKategori.getSelectedItem().toString();
        if (judul.equals("") || pengarang.equals("") || cbKategori.getSelectedIndex() == 0){ 
            JOptionPane.showMessageDialog(this, "Isi field yang kosong");
        } else {
            if (bSubmit.getText().equals("Submit")){
                tambahData (judul, pengarang, kategori);
            } else if (bSubmit.getText().equals("Edit")){
                int barisTerpilih = jtBuku.getSelectedRow();
                ubahData (daftarBuku.get (barisTerpilih).getId(), judul, pengarang, kategori);
            }
        }
        reset();
    }//GEN-LAST:event_bSubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String keyword = tfCari.getText().trim();
        if (keyword.length()==0) {
            loadBuku();
            tampilBuku();
        }else{
            cariBukubyKeyword(keyword);
            tampilBuku();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = jtBuku.getSelectedRow();
        tfJudul.setText (model.getValueAt (barisTerpilih, 0).toString());
        tfPengarang.setText(model.getValueAt (barisTerpilih, 1).toString()); 
        cbKategori.setSelectedItem (model.getValueAt (barisTerpilih, 2));
        bSubmit.setText("Edit");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cariBukubyKeyword (String keyword) {
        if (conn != null) {
        daftarBuku = new ArrayList<>();
        String query = "SELECT * FROM buku WHERE judul LIKE ? OR penulis LIKE ? OR genre LIKE ?";
        try {
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, "%" + keyword + "%"); // Memberikan nilai parameter untuk judul dengan kata kunci
            ps.setString(2, "%" + keyword + "%"); // Memberikan nilai parameter untuk penulis dengan kata kunci
            ps.setString(3, "%" + keyword + "%"); // Memberikan nilai parameter untuk genre dengan kata kunci
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String judul = rs.getString("judul");
                String pengarang = rs.getString("penulis");
                String kategori = rs.getString("genre");
                Buku buku = new Buku(id, judul, pengarang, kategori);
                daftarBuku.add(buku);
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(AppBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }    
            

    private void loadBuku(){
        if(conn!=null){
            daftarBuku = new ArrayList<>();
            String query = "SELECT * FROM buku";
            try{
                PreparedStatement ps = conn.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    int id = rs.getInt("id");
                    String judul = rs.getString("judul");
                    String pengarang = rs.getString("penulis");
                    String kategori = rs.getString("genre");
                    Buku buku = new Buku(id, judul, pengarang, kategori);
                    daftarBuku.add(buku);
               }
                rs.close();
                ps.close();
            }catch (SQLException ex){
                Logger.getLogger(AppBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
   private void tampilBuku(){
        model.setRowCount(0);
        for(Buku b:daftarBuku){
            model.addRow(new Object[]{b.getJudul(),b.getPengarang(),b.getKategori()});
        }
    }
        
    private void reset(){
        tfJudul.setText("");
        tfPengarang.setText("");
        cbKategori.setSelectedIndex(0);
        bSubmit.setText("Submit");
    }        
        
    private void tambahData(String judul, String pengarang, String kategori){
        if (conn != null){
            try{
                String query = "INSERT INTO buku(judul, penulis, genre) values (?,?,?)";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, judul);
                ps.setString(2, pengarang);
                ps.setString(3, kategori);
                int hasil = ps.executeUpdate();
                if (hasil>0){
                    JOptionPane.showMessageDialog(this, "Input Berhasil");
                    //merubah isi tabel
                    loadBuku(); tampilBuku();
                }
            }catch(SQLException ex){
                Logger.getLogger(AppBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void ubahData (int id, String judul, String pengarang, String kategori){
        if (conn != null){
            try {
                String kueri = "UPDATE buku SET judul =?, penulis=2, genre=? WHERE id=?";
                PreparedStatement ps = conn.prepareStatement(kueri);
                ps.setString(1, judul);
                ps.setString (2, pengarang);
                ps.setString(3, kategori);
                ps.setInt(4, id);
                int hasil = ps.executeUpdate();
                if (hasil == 1) {
                    JOptionPane.showMessageDialog(this, "Update Berhasil");
                    //ubah isi tabel
                    loadBuku(); 
                    tampilBuku();
                }
            } catch (SQLException ex) {
                Logger.getLogger (AppBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSubmit;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtBuku;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfPengarang;
    // End of variables declaration//GEN-END:variables
}
